# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fQSoqwkcVWztNKeiFgs0OOH5mM2xvyIJ
"""

import scipy.stats as ss

# Criar um modelo binomial com parâmetros
# n e p

hh = ss.binom(15, 0.4)

ac = hh.pmf(14) + hh.pmf(15)
print(f'a.P(X ≥ 14) = {ac:.5f}\n')
bc = hh.pmf(9) + hh.pmf(10)
print(f'b.P(8 < X ≤ 10) = {bc:.5f}\n')
cc = hh.pmf(0) + hh.pmf(1) + hh.pmf(11) + hh.pmf(12) + hh.pmf(13) + hh.pmf(14) + hh.pmf(15)
print(f'c.P(X < 2 ou X ≥ 11) = {cc:.5f}\n')
dc = hh.pmf(11) + hh.pmf(12) + hh.pmf(13) + hh.pmf(14) + hh.pmf(15)
print(f'd.P(X ≥ 11 ou X > 13) = {dc:.5f}\n')
ec = hh.pmf(4) + hh.pmf(5)
print(f'e.P(X > 3 e X < 6) = {ec:.5f}\n')
fc = (hh.pmf(11) + hh.pmf(12) + hh.pmf(13))/(hh.pmf(11) + hh.pmf(12) + hh.pmf(13) + hh.pmf(14) + hh.pmf(15))
print(f'f.P(X ≤ 13 | X ≥ 11) = {fc:.5f}\n')